INSERT INTO prisondb.rooms SET room_id= 1, room_name="gate1",top_left_x=0,top_left_y=0,bottom_right_x=0,bottom_right_y=0, max_temperature=30, max_noise_level=30, max_light_level=30;
INSERT INTO prisondb.rooms SET room_id= 2, room_name="gate2",top_left_x=0,top_left_y=0,bottom_right_x=0,bottom_right_y=0, max_temperature=30, max_noise_level=30, max_light_level=30;
INSERT INTO prisondb.rooms SET room_id= 3, room_name="Cell Block", top_left_x=200,top_left_y=200,bottom_right_x=650,bottom_right_y=400,max_temperature=30, max_noise_level=30, max_light_level=30;
INSERT INTO prisondb.rooms SET room_id= 4, room_name="Corridor", top_left_x=0,top_left_y=0,bottom_right_x=0,bottom_right_y=0,max_temperature=30, max_noise_level=30, max_light_level=30;
INSERT INTO prisondb.rooms SET room_id= 5, room_name="Courtyard", top_left_x=50,top_left_y=50,bottom_right_x=200,bottom_right_y=550,max_temperature=30, max_noise_level=30, max_light_level=30;
INSERT INTO prisondb.rooms SET room_id= 6, room_name="Canteen", top_left_x=200,top_left_y=400,bottom_right_x=550,bottom_right_y=550,max_temperature=30, max_noise_level=30, max_light_level=30;
INSERT INTO prisondb.rooms SET room_id= 7, room_name="Security Check",top_left_x=550,top_left_y=400,bottom_right_x=750,bottom_right_y=550, max_temperature=30, max_noise_level=30, max_light_level=30;
INSERT INTO prisondb.rooms SET room_id= 8, room_name="Reception",top_left_x=750,top_left_y=400,bottom_right_x=1100,bottom_right_y=550, max_temperature=30, max_noise_level=30, max_light_level=30;
INSERT INTO prisondb.rooms SET room_id= 9, room_name="Visitor Area", top_left_x=750,top_left_y=200,bottom_right_x=1100,bottom_right_y=400,max_temperature=30, max_noise_level=30, max_light_level=30;
INSERT INTO prisondb.rooms SET room_id= 10, room_name="Staff Room", top_left_x=750,top_left_y=50,bottom_right_x=1110,bottom_right_y=200,max_temperature=30, max_noise_level=30, max_light_level=30;
INSERT INTO prisondb.rooms SET room_id= 11, room_name="Cell A",top_left_x=200,top_left_y=50,bottom_right_x=350,bottom_right_y=200, max_temperature=30, max_noise_level=30, max_light_level=30;
INSERT INTO prisondb.rooms SET room_id= 12, room_name="Cell B",top_left_x=350,top_left_y=50,bottom_right_x=500,bottom_right_y=200, max_temperature=30, max_noise_level=30, max_light_level=30;
INSERT INTO prisondb.rooms SET room_id= 13, room_name="Cell C",top_left_x=500,top_left_y=50,bottom_right_x=650,bottom_right_y=200, max_temperature=30, max_noise_level=30, max_light_level=30;
SELECT * FROM prisondb.rooms;